name: test_xbpch
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.6
    - cython
    - dask>=0.14
    - future
    - numpy
    - pytest
    - xarray>=0.12
    - pip:
        - codecov
        - pytest-cov